[package]
name = "cam-pos-system"
version = "0.1.0"
edition = "2021"
authors = ["Christian <chriamue@gmail.com>"]
description = "Capture birds in your garden, running on raspberry pi."
license = "MIT"
readme = "README.md"
repository = "https://github.com/rusty-rails/cam-pos-system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nokhwa = { version = "0.9.4", features = ["input-v4l", "output-threaded"] }
image = { version = "0.23.1", default-features = false, features = [
    "png",
    "jpeg",
] }