[default.shutdown]
ctrlc = false
signals = ["term", "hup"]

[default.objects]
train5 = { id = 5, path = "object1/" }

[default.video_source]
gif = "res/red_train.gif"
#webcam = 0

[release]
port = 8000
address = "0.0.0.0"
